# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# title
#       t.text :description
#       t.date :release_date
#       t.integer :online_rating
#       t.string :poster_path

# movie2= Movie.create(title:"", description:"", release_date:, online_rating:, poster_path: )   

user1= User.create(name: "GTest", email: 'g1@gmail.com', password: '12345678')
user2= User.create(name: 'Milan', email: 'milanm1120@gmail.com', password: '12345678')
user3= User.create(name: 'Bob', email: 'bob@bob.com', password: '12345678')


movie1 = Movie.create(title: "Star Wars", description: "Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.", 
                        release_date: '1977-05-25', online_rating: 8, poster_path: 'poster/SW4.jpg' )
movie2= Movie.create(title:"Star Wars: The Empire Strikes Back", description:"The epic saga continues as Luke Skywalker, in hopes of defeating the evil Galactic Empire, learns the ways of the Jedi from aging master Yoda. But Darth Vader is more determined than ever to capture Luke. Meanwhile, rebel leader Princess Leia, cocky Han Solo, Chewbacca, and droids C-3PO and R2-D2 are thrown into various stages of capture, betrayal and despair.", 
                        release_date: '1990-06-20', online_rating: 8, poster_path: 'poster/SW5.jpg' )
movie3= Movie.create(title:"Star Wars: Return of the Jedi", description:"Luke Skywalker leads a mission to rescue his friend Han Solo from the clutches of Jabba the Hutt, while the Emperor seeks to destroy the Rebellion once and for all with a second dreaded Death Star.",
                        release_date: '1983-05-25', online_rating: 8, poster_path: 'poster/SW6.jpg' )
movie4= Movie.create(title:"Star Wars: Episode I - The Phantom Menace", description:"Anakin Skywalker, a young slave strong with the Force, is discovered on Tatooine. Meanwhile, the evil Sith have returned, enacting their plot for revenge against the Jedi.", 
                        release_date: '1999-05-19', online_rating: 6, poster_path: 'poster/SW1.jpg')   
movie5= Movie.create(title:"Star Wars: Episode II - Attack of the Clones", description:"Following an assassination attempt on Senator Padmé Amidala, Jedi Knights Anakin Skywalker and Obi-Wan Kenobi investigate a mysterious plot that could change the galaxy forever.", 
                        release_date: '2002-05-16', online_rating: 7, poster_path: 'poster/SW2.jpg' )   
movie6= Movie.create(title:"Star Wars: Episode III - Revenge of the Sith", description:"The evil Darth Sidious enacts his final plan for unlimited power -- and the heroic Jedi Anakin Skywalker must choose a side.", 
                        release_date: '2005-05-19', online_rating: 7, poster_path: 'poster/SW3.jpg' )   
movie7= Movie.create(title:"Star Wars: The Force Awakens", description:"Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.", 
                        release_date: '2015-12-18', online_rating: 7, poster_path: 'poster/SW7.jpg' )   
movie8= Movie.create(title:"Star Wars: The Last Jedi", description:"Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.", 
                        release_date: '2017-12-15', online_rating: 7, poster_path: 'poster/SW8.jpg' )   
movie9= Movie.create(title:"Star Wars: The Rise of Skywalker", description:"The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.",
                        release_date: '2019-12-20', online_rating: 7, poster_path: 'poster/SW9.jpg')   
movie10= Movie.create(title:"Rogue One: A Star Wars Story", description:"A rogue band of resistance fighters unite for a mission to steal the Death Star plans and bring a new hope to the galaxy.", 
                        release_date: '2016-12-16', online_rating: 8, poster_path: 'poster/RogueOne.jpg')   
movie11= Movie.create(title:"Solo: A Star Wars Story", description:"Through a series of daring escapades deep within a dark and dangerous criminal underworld, Han Solo meets his mighty future copilot Chewbacca and encounters the notorious gambler Lando Calrissian.",
                        release_date: '2018-05-25', online_rating: 7, poster_path: 'poster/Solo.jpg' )   
movie12= Movie.create(title:"Harry Potter and the Philosopher's Stone", description:"Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard—with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths—and about the villain who's to blame.",
                        release_date: '2001-11-16', online_rating: 8, poster_path: 'poster/HP1.jpg')   
movie13= Movie.create(title:"Harry Potter and the Chamber of Secrets", description:"Cars fly, trees fight back, and a mysterious house-elf comes to warn Harry Potter at the start of his second year at Hogwarts. Adventure and danger await when bloody writing on a wall announces: The Chamber Of Secrets Has Been Opened. To save Hogwarts will require all of Harry, Ron and Hermione’s magical abilities and courage.",
                        release_date:'2002-11-15', online_rating: 8, poster_path: 'poster/HP2.jpg')   
movie14= Movie.create(title:"Harry Potter and the Prisoner of Azkaban", description:"Year three at Hogwarts means new fun and challenges as Harry learns the delicate art of approaching a Hippogriff, transforming shape-shifting Boggarts into hilarity and even turning back time. But the term also brings danger: soul-sucking Dementors hover over the school, an ally of the accursed He-Who-Cannot-Be-Named lurks within the castle walls, and fearsome wizard Sirius Black escapes Azkaban. And Harry will confront them all.", 
                        release_date: '2004-06-04', online_rating: 8, poster_path: 'poster/HP3.jpg')   
movie15= Movie.create(title:"Harry Potter and the Goblet of Fire", description:"When Harry Potter's name emerges from the Goblet of Fire, he becomes a competitor in a grueling battle for glory among three wizarding schools—the Triwizard Tournament. But since Harry never submitted his name for the Tournament, who did? Now Harry must confront a deadly dragon, fierce water demons and an enchanted maze only to find himself in the cruel grasp of He Who Must Not Be Named.", 
                        release_date: '2005-11-18', online_rating: 8, poster_path: 'poster/HP4.jpg')   
movie16= Movie.create(title:"Harry Potter and the Order of the Phoenix", description:"The rebellion begins! Lord Voldemort has returned, but the Ministry of Magic is doing everything it can to keep the wizarding world from knowing the truth – including appointing Ministry official Dolores Umbridge as the new Defence Against the Dark Arts professor at Hogwarts. When Umbridge refuses to teach practical defensive magic, Ron and Hermione convince Harry to secretly train a select group of students for the wizarding war that lies ahead. A terrifying showdown between good and evil awaits in this enthralling film version of the fifth novel in J.K. Rowling’s Harry Potter series. Prepare for battle!",
                        release_date: '2007-07-11', online_rating: 8, poster_path: 'poster/HP5.jpg')   
movie17= Movie.create(title:"Harry Potter and the Half-Blood Prince", description:"As Lord Voldemort tightens his grip on both the Muggle and wizarding worlds, Hogwarts is no longer a safe haven. Harry suspects perils may even lie within the castle, but Dumbledore is more intent upon preparing him for the final battle fast approaching. Together they work to find the key to unlock Voldemorts defenses and to this end, Dumbledore recruits his old friend and colleague Horace Slughorn, whom he believes holds crucial information. Even as the decisive showdown looms, romance blossoms for Harry, Ron, Hermione and their classmates. Love is in the air, but danger lies ahead and Hogwarts may never be the same again.",
                        release_date: '2009-07-08', online_rating: 8, poster_path: 'poster/HP6.jpg')   
movie18= Movie.create(title:"Harry Potter and the Deathly Hallows: Part 1", description:"Harry, Ron and Hermione walk away from their last year at Hogwarts to find and destroy the remaining Horcruxes, putting an end to Voldemort's bid for immortality. But with Harry's beloved Dumbledore dead and Voldemort's unscrupulous Death Eaters on the loose, the world is more dangerous than ever.",
                        release_date: '2010-11-19', online_rating: 8, poster_path: 'poster/HP7-1.jpg')   
movie19= Movie.create(title:"Harry Potter and the Deathly Hallows: Part 2", description:"Harry, Ron and Hermione continue their quest to vanquish the evil Voldemort once and for all. Just as things begin to look hopeless for the young wizards, Harry discovers a trio of magical objects that endow him with powers to rival Voldemort's formidable skills.",
                        release_date: '2011-07-15', online_rating: 8, poster_path: 'poster/HP7-2.jpg')   
movie20= Movie.create(title:"The Godfather", description:"Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
                        release_date: '1972-03-15', online_rating: 9, poster_path: 'poster/TGF1.jpg')   
movie21= Movie.create(title:"The Godfather: Part II", description:"In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
                        release_date: '1974-12-20', online_rating: 9, poster_path: 'poster/TGF2.jpg')   
movie22= Movie.create(title:"The Godfather: Part III", description:"In the midst of trying to legitimize his business dealings in 1979 New York and Italy, aging mafia don, Michael Corleone seeks forgiveness for his sins while taking a young protege under his wing.",
                        release_date: '1990-12-25', online_rating: 8, poster_path: 'poster/TGF3.jpg')   
movie23= Movie.create(title:"Scarface", description:"After getting a green card in exchange for assassinating a Cuban government official, Tony Montana stakes a claim on the drug trade in Miami. Viciously murdering anyone who stands in his way, Tony eventually becomes the biggest drug lord in the state, controlling nearly all the cocaine that comes through Miami. But increased pressure from the police, wars with Colombian drug cartels and his own drug-fueled paranoia serve to fuel the flames of his eventual downfall.",
                        release_date: '1983-12-09', online_rating: 8, poster_path: 'poster/Scarface.jpg')   
movie24= Movie.create(title:"Jurassic Park", description:"A wealthy entrepreneur secretly creates a theme park featuring living dinosaurs drawn from prehistoric DNA. Before opening day, he invites a team of experts and his two eager grandchildren to experience the park and help calm anxious investors. However, the park is anything but amusing as the security systems go off-line and the dinosaurs escape.",
                        release_date: '1993-06-11', online_rating: 8, poster_path: 'poster/JP1.jpg')   
movie25= Movie.create(title:"The Lost World: Jurassic Park", description:"Four years after Jurassic Park's genetically bred dinosaurs ran amok, multimillionaire John Hammond shocks chaos theorist Ian Malcolm by revealing that he has been breeding more beasties at a secret location. Malcolm, his paleontologist ladylove and a wildlife videographer join an expedition to document the lethal lizards' natural behavior in this action-packed thriller.",
                        release_date: '1997-05-23', online_rating: 7, poster_path: 'poster/JP2.jpg')   
movie26= Movie.create(title:"Jurassic Park III", description:"In need of funds for research, Dr. Alan Grant accepts a large sum of money to accompany Paul and Amanda Kirby on an aerial tour of the infamous Isla Sorna. It isn't long before all hell breaks loose and the stranded wayfarers must fight for survival as a host of new -- and even more deadly -- dinosaurs try to make snacks of them.",
                        release_date: '2001-07-18', online_rating: 6, poster_path: 'poster/JP3.jpg')   
movie27= Movie.create(title:"Top Gun", description:"A heart-pounding combination of action, music and incredible aerial photography helped make Top Gun the blockbuster hit. of 1986. Top Gun takes a look at the danger and excitement that awaits every pilot at the Navy's prestigious fighter weapons school. Tom Cruise is superb as Lt. Pete 'Maverick' Mitchell, a daring young flyer who's out to become the best. And Kelly McGillis sizzles as the civilian instructor who teaches Maverick a few things you can't learn in a classroom.",
                        release_date: '1986-05-16', online_rating: 7, poster_path: 'poster/TG1.jpg')   
movie28= Movie.create(title:"The Karate Kid", description:"After some violent confrontations with his new classmates, Daniel LaRusso learns karate from Japanese handyman Mr. Miyagi, in order to defend himself.",
                        release_date: '1984-06-22', online_rating: 7, poster_path: 'poster/KK.jpg') 
movie29= Movie.create(title:"The Karate Kid Part II", description:"After discovering that his father is at death's door, Mr. Miyagi sets out to Japan, to see him with Daniel. Upon arriving, Miyagi must confront an old rival. Meanwhile, Daniel encounters a new love, and some new enemies.",
                        release_date: '1986-06-18', online_rating: 6, poster_path: 'poster/KKII.jpg')
movie30= Movie.create(title:"The Karate Kid Part III", description:"Despondent over the closing of his karate school, Cobra Kai teacher John Kreese joins a ruthless businessman and martial artist to get revenge on Daniel and Mr. Miyagi.",
                        release_date: '1989-06-29', online_rating: 6, poster_path: 'poster/KKIII.jpg')
movie31= Movie.create(title:"Batman Begins", description:"Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City. Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman.",
                        release_date: '2005-06-15', online_rating: 8, poster_path: 'poster/BB1.jpg')
movie32= Movie.create(title:"Batman: The Dark Knight", description:"Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
                        release_date: '2008-07-18', online_rating: 9, poster_path: 'poster/BB2.jpg') 
movie33= Movie.create(title:"Batman: The Dark Knight Rises", description:"Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",
                        release_date: '2012-07-20', online_rating: 8, poster_path: 'poster/BB3.jpg') 
movie34= Movie.create(title:"The Hunger Games", description:"Every year in the ruins of what was once North America, the nation of Panem forces each of its twelve districts to send a teenage boy and girl to compete in the Hunger Games. Part twisted entertainment, part government intimidation tactic, the Hunger Games are a nationally televised event in which “Tributes” must fight with one another until one survivor remains. Pitted against highly-trained Tributes who have prepared for these Games their entire lives, Katniss is forced to rely upon her sharp instincts as well as the mentorship of drunken former victor Haymitch Abernathy. If she’s ever to return home to District 12, Katniss must make impossible choices in the arena that weigh survival against humanity and life against love. The world will be watching.",
                        release_date: '2012-03-23', online_rating: 7, poster_path: 'poster/HG1.jpg') 
movie35= Movie.create(title:"The Hunger Games: Catching Fire", description:"Katniss Everdeen has returned home safe after winning the 74th Annual Hunger Games along with fellow tribute Peeta Mellark. Winning means that they must turn around and leave their family and close friends, embarking on a 'Victor's Tour' of the districts. Along the way Katniss senses that a rebellion is simmering, but the Capitol is still very much in control as President Snow prepares the 75th Annual Hunger Games (The Quarter Quell) - a competition that could change Panem forever.",
                        release_date: '2013-11-22', online_rating: 7, poster_path: 'poster/HG2.jpg') 
movie36= Movie.create(title:"The Hunger Games: Mockingjay - Part 1", description:"Katniss Everdeen reluctantly becomes the symbol of a mass rebellion against the autocratic Capitol.",
                        release_date: '2014-11-21', online_rating: 6, poster_path: 'poster/HG3-1.jpg') 
movie37= Movie.create(title:"The Hunger Games: Mockingjay - Part 2", description:"With the nation of Panem in a full scale war, Katniss confronts President Snow in the final showdown. Teamed with a group of her closest friends including Gale, Finnick, and Peeta Katniss goes off on a mission with the unit from District 13 as they risk their lives to stage an assassination attempt on President Snow who has become increasingly obsessed with destroying her. The mortal traps, enemies, and moral choices that await Katniss will challenge her more than any arena she faced in The Hunger Games.",
                        release_date: '2015-11-20', online_rating: 7, poster_path: 'poster/HG3-2.jpg') 
movie38= Movie.create(title:"Spider-Man: Homecoming", description:"Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.",
                        release_date: '2017-07-07', online_rating: 7, poster_path: 'poster/SM1.jpg') 
movie39= Movie.create(title:"Spider-Man: Far From Home", description:"Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.",
                        release_date: '2019-02-07', online_rating: 8, poster_path: 'poster/SM2.jpg') 
movie40= Movie.create(title:"Spider-Man: No Way Home", description:"Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
                        release_date: '2021-12-17', online_rating: 9, poster_path: 'poster/SM3.jpg') 
movie2= Movie.create(title:"Jaws", description:"When an insatiable great white shark terrorizes the townspeople of Amity Island, the police chief, an oceanographer and a grizzled shark hunter seek to destroy the blood-thirsty beast.",
                        release_date: '1975-06-20', online_rating: 8, poster_path: 'poster/JS1.jpg') 
movie2= Movie.create(title:"Jaws 2", description:"Police chief Brody must protect the citizens of Amity after a second monstrous shark begins terrorizing the waters.",
                        release_date: '1978-06-16', online_rating: 6, poster_path: 'poster/JS2.jpg') 
movie2= Movie.create(title:"Jaws 3", description:"This third film in the series follows a group of marine biologists attempting to capture a young great white shark that has wandered into Florida's Sea World Park. However, later it is discovered that the shark's 35-foot mother is also a guest at Sea World. What follows is the shark wreaking havoc on the visitors in the park.",
                        release_date: '1983-07-22', online_rating: 4, poster_path: 'poster/JS3.jpg') 
movie2= Movie.create(title:"Rocky", description:"When world heavyweight boxing champion, Apollo Creed wants to give an unknown fighter a shot at the title as a publicity stunt, his handlers choose palooka Rocky Balboa, an uneducated collector for a Philadelphia loan shark. Rocky teams up with trainer Mickey Goldmill to make the most of this once in a lifetime break.",
                        release_date: '1976-11-21', online_rating: 8, poster_path: 'poster/RK1.jpg') 
movie2= Movie.create(title:"Rocky II", description:"After Rocky goes the distance with champ Apollo Creed, both try to put the fight behind them and move on. Rocky settles down with Adrian but can't put his life together outside the ring, while Creed seeks a rematch to restore his reputation. Soon enough, the 'Master of Disaster' and the 'Italian Stallion' are set on a collision course for a climactic battle that is brutal and unforgettable.",
                        release_date: '1979-06-15', online_rating: 7, poster_path: 'poster/RK2.jpg') 
movie2= Movie.create(title:"Rocky III", description:"Now the world champion, Rocky Balboa is living in luxury and only fighting opponents who pose no threat to him in the ring, until Clubber Lang challenges him to a bout. After taking a pounding from Lang, the humbled champ turns to former bitter rival Apollo Creed for a rematch with Lang.",
                        release_date: '1982-05-28', online_rating: 7, poster_path: 'poster/RK3.jpg') 
movie2= Movie.create(title:"Rocky IV", description:"After iron man Drago, a highly intimidating 6-foot-5, 261-pound Soviet athlete, kills Apollo Creed in an exhibition match, Rocky comes to the heart of Russia for 15 pile-driving boxing rounds of revenge.",
                        release_date: '1985-11-21', online_rating: 7, poster_path: 'poster/RK4.jpg') 
movie2= Movie.create(title:"Rocky V", description:"A lifetime of taking shots has ended Rocky’s career, and a crooked accountant has left him broke. Inspired by the memory of his trainer, however, Rocky finds glory in training and takes on an up-and-coming boxer.",
                        release_date: '1990-11-16', online_rating: 6, poster_path: 'poster/RK5.jpg') 
movie2= Movie.create(title:"300", description:"Based on Frank Miller's graphic novel, '300' is very loosely based the 480 B.C. Battle of Thermopylae, where the King of Sparta led his army against the advancing Persians; the battle is said to have inspired all of Greece to band together against the Persians, and helped usher in the world's first democracy.",
                        release_date: '2007-03-09', online_rating: 7, poster_path: 'poster/300-1.jpg') 
movie2= Movie.create(title:"300: Rise Of An Empire", description:"Greek general Themistokles attempts to unite all of Greece by leading the charge that will change the course of the war. Themistokles faces the massive invading Persian forces led by mortal-turned-god, Xerxes and Artemesia, the vengeful commander of the Persian navy.",
                        release_date: '2014-03-07', online_rating: 6, poster_path: 'poster/300-2.jpg')    
